# Generated by Django 5.1.1 on 2024-11-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("address", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(upload_to="building/images/building_image"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("owner", models.ManyToManyField(to="owners.owner")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("room", models.IntegerField()),
                ("toilet", models.IntegerField()),
                ("window", models.IntegerField()),
                ("image", models.ImageField(upload_to="building/images/unit_image")),
                ("is_occupied", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="building.building",
                    ),
                ),
            ],
            options={
                "ordering": ["updated"],
            },
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["-created"], name="building_bu_created_ed969d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["is_occupied", "updated"], name="building_un_is_occu_780b71_idx"
            ),
        ),
    ]
