# Generated by Django 5.1.1 on 2024-11-15 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
        ("tenants", "0002_remove_tenant_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit",
                to="building.building",
            ),
        ),
    ]
