# Generated by Django 5.1.1 on 2024-11-15 06:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0002_unit_tenant_alter_unit_building"),
        ("tenants", "0002_remove_tenant_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="building.building",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="room",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="toilet",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="window",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
