# Generated by Django 5.1.1 on 2024-11-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0003_alter_building_address_alter_building_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="building/images/building_image"
            ),
        ),
    ]
