# Generated by Django 5.1.1 on 2024-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0004_alter_building_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="building/images/unit_image"
            ),
        ),
    ]
